version: '3.7'

services:
  gen:
    build: .
    image: attestation-covid19
    volumes:
      - ./config/config.inc:/data/config/config.inc:ro
#      - ./build:/data/build
      - ./results:/results
    environment:
      - RESULT_PATH=/results/

