version: '3.7'

services:
  
  attestation:
    build: .
    image: attestation-covid19
    volumes:
      - ./config/config.inc.example:/data/config/config.inc:ro
#      - ./build:/data/build
#      - ./results:/results
    ports:
      - 5000:5000
#    environment:
#      - RESULT_PATH=/results/
